version: '3'

services:
    postgres-compose:
      image: postgres
      environment:
        POSTGRES_PASSWORD: "T*WCHEhUny7ZE#nG4LQv4*ZLdPH#EoZcR9LxzVSHpyUedJitmDkXA^h@tQ#gsJWFnRJdzuc&kXT^G3LxJ!mrk4vBexHDyd#oxzxhCg8KpJpt8yY5gH^tWpzWJh2#sq3y"
      ports:
        - "15432:5432"
      volumes:
        - miniCastleBDD:/var/lib/postgresql/data
      networks:
        - postgres-compose-network

    pgadmin-compose:
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: "email@gmail.com"
        PGADMIN_DEFAULT_PASSWORD: "rVrP6kucvgm%JPMkDoYSfvB3tPXUgP4^DMwZY6K3r@VgD!ot7spH8hhUH@jpWMGxx#CnTe794Vt%2apfRxm8bo4o^Wc!U&uTUtKGC!cKwekrtFFQWj&jpc7dG6!CCxLt"
      ports:
        - "16543:80"
      depends_on:
        - postgres-compose
      networks:
        - postgres-compose-network

networks:
    postgres-compose-network:
      driver: bridge

volumes:
  miniCastleBDD: